server.port=8081

simulator.cors.allowed-origins=http://localhost:3000,http://localhost:5173

simulator.max-safe-temperature-celsius=40
simulator.max-safe-duration-minutes=60
simulator.random-seed=42

simulator.sensors.transport.violation-probability=0.1
simulator.sensors.warehouse.violation-probability=0.1
simulator.sensors.defrost.violation-probability=0.1

simulator.web3.rpc-url=http://localhost:8545

spring.config.import=optional:file:./application-local.properties
